### ISSUE TITLE
Issues with Path Following Dynamics and Lyapunov condition 

### ISSUE THREAD

**Issue by jlwu002** [RuikunZhou/Unknown_Neural_Lyapunov#2]
Dear Ruikun,

Thank you for your interesting work. We have conducted a follow-up study on your research, where we solved for a controller and certified the Lyapunov conditions for arbitrary nonlinear dynamical systems in the discrete-time setting: https://github.com/jlwu002/nlc_discrete (NeurIPS 2023), [paper](https://arxiv.org/pdf/2305.06547.pdf).

While reproducing your work, we found the following two issues:

1) Issue with Path Following Dynamics. 
There appears to be a typo in the path following dynamics formula: the dynamic for $\dot{\theta}$ (angle error) should use $\dot{d_e}$ in the denominator (where $d_e$ is the distance error), instead of $d_e$ as currently written in the paper and code. The correct dynamic should be: $\dot{\theta}_e = \frac{\omega - v\kappa(s) \cos(\theta_e)}{1 - \dot{d_e}\kappa(s)}$, instead of: $\dot{\theta}_e = \frac{\omega - v\kappa(s) \cos(\theta_e)}{1 - d_e\kappa(s)}$ ([Snider [2009]](https://www.ri.cmu.edu/pub_files/2009/2/Automatic_Steering_Methods_for_Autonomous_Automobile_Path_Tracking.pdf), [Chang [2019]](https://yachienchang.github.io/NeurIPS2019/paper/Neural_Lyapunov_Control_Appendix.pdf))

2) Issue with Lyapunov conditions. 
In your code, the function "CheckLyapunov" checks for the condition V >= 0 and lie_derivative_of_V <= epsilon. However, there is another critical constraint for Lyapunov conditions: V(0) = 0. Since the neural network structure used in your work include bias terms (z1 = np.dot(vars_,w1.T)+b1; z2 = np.dot(a1,w2.T)+b2; V_learn = tanh(z2.item(0))), V(0) = 0 is not guaranteed. This will cause issues, for example, the system cannot distinguish between the equilibrium point and other points with the same value.  We need to check V(x_t) - V(0) > 0.

Thank you!
Junlin

**Comment by RuikunZhou** [comment]
Hi Junlin,

Thanks for your comments and for sharing your interesting work.

Regarding the two issues you mentioned, please see the following responses.

1. I believe the formula for the unicycle path following in my paper is correct, which is Eq. (20) in the appendix. Firstly, we used the unicycle model from [Carona [2008]](https://www.researchgate.net/publication/237425415_CONTROL_OF_UNICYCLE_TYPE_ROBOTS_Tracking_Path_Following_and_Point_Stabilization) in our experiments, instead of the bicycle model. Also, regarding the bicycle model for path following, we carefully investigated this example when writing this paper. It seems that the derivation of the formula in the paper you cited is incorrect, which might also result in the incorrect formula for the path following example in the appendix of the [Neural Lyapunov Control](https://papers.nips.cc/paper_files/paper/2019/hash/2647c1dba23bc0e0f9cdf75339e120d2-Abstract.html) paper.  Here is why:
In that paper, they use $\dot{\theta_p}(s) = \kappa(s)\dot{s}$ and $\dot{s}=v_1 \cos(\theta_e) + \dot{\theta_p} e_{ra}$ to derive Eq. (12). By substituting the former one into the latter one, we have: $(1-\kappa(s) e_{ra}) \dot{s} = v_1 \cos(\theta_e)$. Clearly, we have $\dot{s} = \frac{\cos(\theta_e)}{1 - e_{ra}\kappa(s)} v_1$. Substituting this and $\dot{\theta_p}(s) = \kappa(s)\dot{s}$ into $\dot{\theta_e} = \dot{\theta} - \dot{\theta_p}(s)$, yields,
$$\dot{\theta_e} = \( \frac{\tan(\delta)}{L} - \frac{\kappa(s)\cos(\theta_e)}{1 - e_{ra}\kappa(s)} \) v_1.$$
Clearly, in the second term in the bracket, it should be $e_{ra}$ in the denominator, instead of $\dot{e}_{ra}$. If you are interested in the derivation of the kinematics model of the bicycle, I strongly recommend you to see the detailed and correct derivation in [De Luca [2005]](https://www.di.ens.fr/jean-paul.laumond/promotion/chap4.pdf).

More importantly, with the correct formula as Eq. (20) in our paper, by setting $\kappa(s) = 1$, we have it is a 2-dimensional autonomous system. However, if we have $\dot{d_e}$ in the denominator, it is obviously not.

2.  As we discussed during the rebuttal on [Openreview](https://openreview.net/forum?id=QvlcRh8hd8X&referrer=%5Bthe%20profile%20of%20Ruikun%20Zhou%5D(%2Fprofile%3Fid%3D~Ruikun_Zhou1)) (response to Q4 from Reviewer KQuS), the condition $V(0) = 0$ is not computational enforceable with the SMT solver, dReal. It is not rigorously a Lyapunov function, but with reasonable assumptions, Assumptions 3 & 4, we showed the origin is asymptotically stable. 

Moreover, we fixed this issue by proposing more rigorous verification process with mathematical proofs as a side result in our newly published papers.
+ [Towards Learning and Verifying Maximal Neural Lyapunov Functions](https://arxiv.org/abs/2304.07215), IEEE CDC 2023, 
and the journal version
+ [Physics-Informed Neural Network Lyapunov Functions: PDE Characterization, Learning, and Verification](https://arxiv.org/abs/2312.09131), submitted to Automatica.
By introducing an algorithm with verifying the local stability first and then on a larger region, we showed that the origin is indeed asymptotically stable without any assumptions. Please see Section V in our 2023 CDC paper and Section 5 in the journal version for details. It is also worth mentioning that the maximal region of attraction of the nonlinear systems can be captured with the proposed approach. 

Thanks.
